//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beats1
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public admin()
        {
            this.canremoves = new HashSet<canremove>();
            this.song_add = new HashSet<song_add>();
        }
    
        public int admin_id { get; set; }
        public string password { get; set; }
        public string username { get; set; }
    
        public virtual ICollection<canremove> canremoves { get; set; }
        public virtual ICollection<song_add> song_add { get; set; }
    }
}
