//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beats1
{
    using System;
    using System.Collections.Generic;
    
    public partial class canremove
    {
        public int admin_id { get; set; }
        public string user_name { get; set; }
        public System.DateTime time { get; set; }
        public int id { get; set; }
    
        public virtual admin admin { get; set; }
    }
}
