//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beats1
{
    using System;
    using System.Collections.Generic;
    
    public partial class channel
    {
        public channel()
        {
            this.uploads = new HashSet<upload>();
            this.usercreatedchannels = new HashSet<usercreatedchannel>();
            this.userfollowschannels = new HashSet<userfollowschannel>();
        }
    
        public int channel_id { get; set; }
        public string channel_name { get; set; }
        public string channel_description { get; set; }
        public int follow { get; set; }
    
        public virtual ICollection<upload> uploads { get; set; }
        public virtual ICollection<usercreatedchannel> usercreatedchannels { get; set; }
        public virtual ICollection<userfollowschannel> userfollowschannels { get; set; }
    }
}
