//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beats1
{
    using System;
    using System.Collections.Generic;
    
    public partial class correlation
    {
        public int Id { get; set; }
        public int user1 { get; set; }
        public int user2 { get; set; }
        public double factor { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user3 { get; set; }
    }
}
