//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beats1
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public int h_id { get; set; }
        public int user_id { get; set; }
        public Nullable<int> ratings { get; set; }
        public int song_id { get; set; }
        public int count { get; set; }
        public System.DateTime time { get; set; }
    
        public virtual user user { get; set; }
        public virtual song song { get; set; }
    }
}
