//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beats1
{
    using System;
    using System.Collections.Generic;
    
    public partial class song_add
    {
        public int song_id { get; set; }
        public int admin_id { get; set; }
        public System.DateTime upload_time { get; set; }
        public string path { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual song song { get; set; }
    }
}
