//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beats1
{
    using System;
    using System.Collections.Generic;
    
    public partial class song
    {
        public song()
        {
            this.histories = new HashSet<history>();
            this.song_add = new HashSet<song_add>();
            this.songgenres = new HashSet<songgenre>();
        }
    
        public int song_id { get; set; }
        public string track { get; set; }
        public string artist { get; set; }
        public string album { get; set; }
        public string duration { get; set; }
        public double song_rating { get; set; }
        public int count { get; set; }
        public int counttoday { get; set; }
    
        public virtual ICollection<history> histories { get; set; }
        public virtual ICollection<song_add> song_add { get; set; }
        public virtual ICollection<songgenre> songgenres { get; set; }
    }
}
