//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beats1
{
    using System;
    using System.Collections.Generic;
    
    public partial class upload
    {
        public int trailer_id { get; set; }
        public int channel_id { get; set; }
        public System.DateTime upload_time { get; set; }
        public string path { get; set; }
    
        public virtual channel channel { get; set; }
        public virtual trailer trailer { get; set; }
    }
}
