//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beats1
{
    using System;
    using System.Collections.Generic;
    
    public partial class userfollowschannel
    {
        public int Id { get; set; }
        public int userid { get; set; }
        public int channelid { get; set; }
    
        public virtual channel channel { get; set; }
        public virtual user user { get; set; }
    }
}
