//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beats1
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.correlations = new HashSet<correlation>();
            this.correlations1 = new HashSet<correlation>();
            this.histories = new HashSet<history>();
            this.usercreatedchannels = new HashSet<usercreatedchannel>();
            this.userfollowschannels = new HashSet<userfollowschannel>();
        }
    
        public int user_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string security_ques { get; set; }
        public string security_ans { get; set; }
    
        public virtual ICollection<correlation> correlations { get; set; }
        public virtual ICollection<correlation> correlations1 { get; set; }
        public virtual ICollection<history> histories { get; set; }
        public virtual ICollection<usercreatedchannel> usercreatedchannels { get; set; }
        public virtual ICollection<userfollowschannel> userfollowschannels { get; set; }
    }
}
